export default {
  id: 135,
  pagetitle: 'Монинг дью',
  longtitle: null,
  description: null,
  alias: 'moning-dyu',
  link_attributes: null,
  published: true,
  pub_date: null,
  unpub_date: null,
  parent: 40,
  isfolder: false,
  introtext: null,
  content: null,
  template: 5,
  menuindex: 22,
  searchable: true,
  cacheable: true,
  createdon: 1543759581,
  editedon: 1544194318,
  deleted: false,
  publishedon: 1543759560,
  menutitle: null,
  hidemenu: false,
  uri: 'product/monobuketyi/gotovyie-buketyi/moning-dyu.html',
  uri_override: false,
  properties: null,
  tvs: {
    product_pack: {
      tv_id: 6,
      caption: 'Упаковка',
      category: 6,
      value_id: 346,
      value: 'Крафт бумага, Атласная лента',
    },

    product_count: {
      tv_id: 7,
      caption: 'Количество',
      category: 6,
      value_id: 347,
      value: 19,
    },

    product_composition: {
      tv_id: 19,
      caption: 'Состав',
      category: 6,
      value_id: 348,
      value: 'Розы',
    },

    image: {
      tv_id: 3,
      caption: null,
      category: 5,
      value_id: 384,
      value: 'https://gromovaflowers.ru/assets/images/products/МОНО/100-010.jpg',
    },
  },

  image: 'https://gromovaflowers.ru//assets/images/products/МОНО/100-010.jpg',
  price: {
    value: 36000,
    format: '36 000',
    currency: 'Р',
  },
  old_price: null,
};
